// import Image from "next/image";
export const designWorks = [
    {
    slug: "project1",
    title: "洋風料理屋 Bistro Lumière｜Web広告用バナー",
    description:" \n 25~40代の都市部在住の方をターゲットに、デートや記念日など少し特別な外食シーンを想定して制作した洋風料理店のWeb広告バナーです。\n 写真をメインに使用し、文字量を抑えて余白をしっかりと確保することで、上品で落ち着いた雰囲気を演出しました。\n 予約への導線も意識し、「Web予約はこちら」のCTAボタンを配置。 \n 電話だけでなくWeb予約にも対応していることを視覚的に示し、ユーザーがスムーズに行動できるよう設計しました。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約2時間  \n 〇自主制作作品",
    image:"/Image/フランス料理.png",
  },
  {
    slug: "project2",
    title: "Cafe RIVARNO｜架空カフェ Webサイトトップページ",
    description: "\n 20~40代の男女をターゲットにした、架空カフェのWebサイトトップページを制作しました。 \n カフェやスイーツが好きで、SNSをきっかけに来店を検討するユーザーを想定しています。\n 店舗の雰囲気が一目で伝わるよう外観写真を大きく配置し、来店・予約につながるようCTAボタンを視認性の高い位置に設置しています。 \n メニューセクションでは、写真・商品名・価格を整理し、人気商品が直感的に分かる構成にすることで、来店時のイメージがしやすいよう工夫しました。 \n 初回制作時は雰囲気重視のデザインになってしまい、来店導線が弱い点が課題でした。\n そのため、CTAの配置やコピーの見直し、メニュー情報の整理を行い、「見て終わるサイト」ではなく「行動につながるサイト」になるよう改善しました。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約3時間30分  \n 〇自主制作作品",
    image:"/Image/",
  },
  {
    slug: "project3",
    title: "麺処ヨルノトリ｜Web広告用バナー",
    description:"\n 20~30代の仕事終わりの社会人をターゲットに、深夜営業のラーメン店を想定したWeb広告バナーを制作しました。 \n 「疲れた夜に染みる、背徳系ラーメン」をコンセプトに、終電前後の空腹や罪悪感と欲求が入り混じる心理に訴求するデザインを意識しています。 \n デザインはダークな背景に対して文字の白と黄色で視認性を高めました。 \n また「深夜1:00まで」の営業時間表記を入れることで、終電前に駆け込みやすいことをアピールしています。",
    // contenttitle:"テストテスト",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約2時間30分  \n 〇自主制作作品",
    image:"/Image/ラーメン.png",
  },
  {
    slug: "project4",
    title: "WCB モール｜Web広告用バナー",
    description:" \n クリスマスシーズンに実施されるショッピングモールのセール告知を想定した、Web広告バナーを制作しました。 \n 「ポップで楽しい」をキーワードに、キャッチコピーである「Christmas Sale 最大60%OFF」を大きく配置し、にぎやかで目を引くデザインを意識しています。 \n すべての文字を同じ大きさにするのではなく、ジャンプ率や文字の配置を調整することで、セール内容が一目で伝わるよう工夫しました。 \n 配色はクリスマスを連想しやすい赤を背景に、白文字で可読性を確保し、日付部分には緑を使用しています。 \n また、そりのイラストを取り入れることで、季節感と楽しさを演出しました。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約4時間 \n ※「バナーデザイン練習10本ノック」の課題をもとに制作した自主制作作品です。\n [https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8](https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8)",
    image:"/Image/クリスマス.png",
  },
  {
    slug: "project5",
    title: "WCB 個別塾｜Web広告用バナー",
    description:" \n 国立大学を目指す高校生の男女およびその保護者をターゲットに、個別指導塾の夏期講習生募集を目的としたWeb広告バナーを制作しました。\n 真面目さや誠実さ、信頼感が伝わるよう、テーマカラーである青色を軸に、白と黄色を組み合わせた配色で構成しています。\n 掲載する情報は、ユーザーが一目で内容を把握できるよう「夏期講習受付中」「7.30 START」「この夏、苦手を克服しよう」の3点に絞り、情報量を抑えました。 \n また、文字のジャンプ率や配置を意識し、視認性が高く、重要な情報が自然と目に入るレイアウトを心がけています。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約4時間 \n ※「バナーデザイン練習10本ノック」の課題をもとに制作した自主制作作品です。\n [https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8](https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8)",
    image:"/Image/塾.png",
  },
  {
    slug: "project6",
    title: "WCB ランニングクラブ｜Web広告用バナー",
    description:" \n スポーツが好きで、平日の仕事前後や週末も積極的にトレーニングしている大人をターゲットに、運動教室のWeb広告バナーを制作しました。\n さわやかさと躍動感のある印象を与えるため、全体の配色は青を基調としています。\n 「入会金0円」というサブテキストは、視認性を高めるため黄色の円で囲み、目立たせました。 \n また、CTAボタンを右下に配置し、「今すぐ相談」という文言を使用することで、ユーザーが次の行動に移りやすい構成を意識しています。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約4時間 \n ※「バナーデザイン練習10本ノック」の課題をもとに制作した自主制作作品です。\n [https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8](https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8)",
    image:"/Image/スポーツ.png",
  },
  {
    slug: "project7",
    title: "WCB Travel｜Web広告用バナー",
    description:" \n 50~60代の方をターゲットにした、海外旅行のWeb広告バナーを制作しました。\n 「優雅な旅」をキーワードに、白や金を基調とした配色を用い、高級感と上品さのある世界観を意識しています。\n メインコピーは背景写真と調和するよう配置し、全体に統一感が出るよう工夫しました。 \n また、CTAボタンにも金色を使用することで、視認性を確保しつつ、サービスの上質さが伝わるデザインにしています。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約4時間 \n ※「バナーデザイン練習10本ノック」の課題をもとに制作した自主制作作品です。\n [https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8](https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8)",
    image:"/Image/旅行.png",
  },
  {
    slug: "project8",
    title: "WCB Shampoo｜Web広告用バナー",
    description:" \n 10~20代女性をターゲットにした、シャンプー商品のWeb広告バナーを制作しました。\n 「かわいさ・手軽さ・楽しさ」をキーワードに、ピンクを基調としたやわらかい配色と、透明感のある背景で親しみやすさを表現しています。\n 商品写真を大きく配置することで、視認性とブランド認知の向上を意識しています。",
    // contenttitle:"工夫した点・学んだこと",
    content:"\n 〇使用ツール：Figma \n 〇制作時間：約5時間 \n ※「バナーデザイン練習10本ノック」の課題をもとに制作した自主制作作品です。\n [https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8](https://www.webcreatorbox.com/blog/banner-design-10#haae6f2c3b8)",
    image:"/Image/シャンプー.png",
  },
];
